CREATE TABLE CENTROS_FORENSES(
id INT PRIMARY KEY,
nombre VARCHAR(150) NOT NULL,
pais VARCHAR(150) NOT NULL,
nivel_seguridad INT NOT NULL,
autor_examen VARCHAR(150) NOT NULL
);


CREATE TABLE MUESTRAS_FORENSES(
id INT PRIMARY KEY,
codigo_caso INT NOT NULL,
tipo_muestra VARCHAR(150) NOT NULL,
fecha_recogida DATE,
estado_custodia VARCHAR(150) NOT NULL,
centro_id INT NOT NULL,
autor_examen VARCHAR(150) NOT NULL,
CONSTRAINT FK_MUESTRA_CENTRO
        FOREIGN KEY (centro_id) REFERENCES CENTROS_FORENSES(id)
);


CREATE TABLE INFORMES_FORENSES(
id INT PRIMARY KEY,
adn_positivo BOOLEAN NOT NULL DEFAULT false,
nivel_riesgo INT NOT NULL,
conclusion VARCHAR(150) NOT NULL,
muestra_id INT NOT NULL UNIQUE,
autor_examen VARCHAR(150) NOT NULL,
CONSTRAINT FK_INFORMES_FORENSES
        FOREIGN KEY (muestra_id) REFERENCES MUESTRAS_FORENSES(id)

);