CREATE TABLE CENTROS_FORENSES(
ID INT PRIMARY KEY,
NOMBRE VARCHAR(150) NOT NULL,
PAIS VARCHAR(150) NOT NULL,
NIVEL_SEGURIDAD INT NOT NULL,
AUTOR_EXAMEN VARCHAR(150) NOT NULL
);


CREATE TABLE MUESTRAS_FORENSES(
ID INT PRIMARY KEY,
CODIGO_CASO INT NOT NULL,
TIPO_MUESTRA VARCHAR(150) NOT NULL,
FECHA_RECOGIDA DATE,
ESTADO_CUSTODIA VARCHAR(150) NOT NULL,
CENTRO_ID INT NOT NULL,
AUTOR_EXAMEN VARCHAR(150) NOT NULL,
CONSTRAINT FK_MUESTRA_CENTRO
        FOREIGN KEY (CENTRO_ID) REFERENCES CENTROS_FORENSES(ID)
);


CREATE TABLE INFORMES_FORENSES(
ID INT PRIMARY KEY,
ADN_POSITIVO BOOLEAN NOT NULL DEFAULT false,
NIVEL_RIESGO INT NOT NULL,
CONCLUSION VARCHAR(150) NOT NULL,
MUESTRA_ID INT NOT NULL UNIQUE,
AUTOR_EXAMEN VARCHAR(150) NOT NULL,
CONSTRAINT FK_INFORMES_FORENSES
        FOREIGN KEY (MUESTRA_ID) REFERENCES MUESTRAS_FORENSES(id)
);














