INSERT INTO CENTROS_FORENSES(ID, NOMBRE, PAIS, NIVEL_SEGURIDAD, AUTOR_EXAMEN) VALUES
(1,'EST','ESPAÑA',6,'VICTOR BONILLA'),
(2,'ENT','INGLATERRA',7,'VICTOR BONILLA'),
(3,'GET','ALEMANIA',4,'VICTOR BONILLA'),
(4,'FRT','FRANCIA',6,'VICTOR BONILLA'),
(5,'JPT','JAPON',8,'VICTOR BONILLA');



INSERT INTO MUESTRAS_FORENSES(ID, CODIGO_CASO, TIPO_MUESTRA, FECHA_RECOGIDA, ESTADO_CUSTODIA, CENTRO_ID, AUTOR_EXAMEN) VALUES
(1,1,'SANGRE',16/12/2022,'PROTEGIDO',1,'VICTOR BONILLA'),
(2,2,'PELO',12/11/2023,'ROBADO',2,'VICTOR BONILLA'),
(3,3,'SALIVA',13/10/2021,'OBSERVACION',3,'VICTOR BONILLA'),
(4,4,'SANGRE',14/9/2020,'ELIMINADO',4,'VICTOR BONILLA'),
(5,5,'PELO',15/8/2025,'PROTEGIDO',5,'VICTOR BONILLA');


INSERT INTO INFORMES_FORENSES(ID, ADN_POSITIVO, NIVEL_RIESGO, CONCLUSION, MUESTRA_ID, AUTOR_EXAMEN) VALUES
(1,'TRUE',4,'CONCLUIDO',1,'VICTOR BONILLA'),
(2,'FALSE',7,'NO CONCLUIDO',2,'VICTOR BONILLA'),
(3,'TRUE',8,'SOSPECHA',3,'VICTOR BONILLA'),
(4,'FALSE',5,'NOVEDAD',4,'VICTOR BONILLA'),
(5,'TRUE',3,'CONCLUIDO',5,'VICTOR BONILLA');