
-- CRUD básico
SELECT * FROM CENTROS_FORENSES ORDER BY ID;
SELECT * FROM CENTROS_FORENSES WHERE ID = 1;

SELECT * FROM MUESTRAS_FORENSES ORDER BY ID;
SELECT * FROM MUESTRAS_FORENSES WHERE ID = 1;
SELECT * FROM MUESTRAS_FORENSES WHERE CENTRO_ID = 1 ORDER BY CODIGO_CASO;

-- INNER JOIN 1:1 — muestra con su informe
SELECT M.ID, M.CODIGO_CASO, M.TIPO_MUESTRA, M.FECHA_RECOGIDA, M.ESTADO_CUSTODIA, M.CENTRO_ID,
       I.ID, I.ADN_POSITIVO, I.NIVEL_RIESGO, I.CONCLUSION
FROM MUESTRAS_FORENSES M
INNER JOIN INFORMES_FORENSES I ON M.ID = I.MUESTRA_ID
WHERE M.ID = 1;

